services:
  spring_secure_api:
    container_name: tienda
    build: ./spring-secure-api
    ports:
      - "80:8080"
    environment:
      DB_URL: jdbc:mysql://db:3306/tienda?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USER_NAME: user
      DB_PASSWORD: user
      JWT_EXPIRATION: 30
      JWT_SECRET_KEY: h9a6p2m9XQ8fgjldRHLv7EwP6+MTODFSfJ4I8gZ0tjo=
    restart: always
    depends_on:
      db:
        condition: service_healthy
    networks:
      - tienda_net

  db:
    container_name: db
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: tienda
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uuser", "-puser"]
      timeout: 10s
      retries: 10
    networks:
      - tienda_net

volumes:
  mysql_data:
    driver: local

networks:
  tienda_net:
    driver: bridge